example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
import imp
from django.urls import path
from katalog.views import show_catalog

app_name =  'katalog'

urlpatterns = [
    path('', show_catalog ,name='show_catalog')
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_json_by_id, show_mywatchlist, show_xml_by_id
from mywatchlist.views import show_xml
from mywatchlist.views import show_json

app_name =  'mywatchlist'

urlpatterns = [
    path('', show_mywatchlist, name='show_mywatchlist'),
    path('html/', show_mywatchlist, name = 'show_mywatchlist'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>', show_xml_by_id, name = 'show_xml_by_id'),
    path('json/<int:id>', show_json_by_id, name = 'show_json_by_id'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

todolist/urls.py
from django.urls import path
from todolist.views import *

app_name = 'todolist'

urlpatterns = [ 
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name = 'login'),
    path('logout/', logout_user, name = 'logout'),
    path('create-task/', create_task, name='create_task'),
    path('status/<int:id>/', status, name='status'),
    path('delete/<int:id>/', delete, name='delete'),
    path('json/', show_json_by_id, name='show_json_by_id'),
    path('add/', create_task_ajax, name='create_task_ajax'),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

# Create your models here.
class watchList(models.Model):
    watched = models.CharField(max_length = 50)
    title = models.CharField(max_length = 80)
    rating = models.IntegerField()
    release_date = models.CharField(max_length = 60)
    review = models.TextField()

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task (models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE, blank = True, null = True)
    date = models.DateField(auto_now=True)
    title = models.CharField(max_length=250)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from django.forms import ModelForm
from todolist.models import Task

class Input_Form(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description']

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

def show_catalog(request):
    getCatalogs = CatalogItem.objects.all()
    context = {
        'Name' : 'Alizha',
        'Student_ID' : '2106652000',
        'catalogs' : getCatalogs
    }

    return render(
        request,
        'katalog.html',
        context
    )

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import watchList
from django.http import HttpResponse
from django.core import serializers

# Create your views here.
def show_mywatchlist(request):
    getWatchList = watchList.objects.all()
    context = {
        'Name' : 'Alizha',
        'Student_ID' : '2106652000',
        'watchlist' : getWatchList
    }
    return render(request, "mywatchlist.html", context)

def show_xml(request):
    data = watchList.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = watchList.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = watchList.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type ="application/xml")

def show_json_by_id(request, id):
    data = watchList.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type = "application/json")

todolist/views.py
from django.shortcuts import render
from todolist.forms import Input_Form
from todolist.models import Task
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt

@login_required(login_url='/todolist/login')
def show_todolist(request):
    getToDoList = Task.objects.filter(user=request.user)
    context = {
        'username': request.user,
        'to_do_list' : getToDoList,
    }
    return render(request, "todolist.html", context)

@login_required(login_url='/todolist/login/')
@csrf_exempt
def create_task(request):
    form = Input_Form()

    if request.method == "POST":
        form = Input_Form(request.POST)
        form.instance.user = request.user
        if form.is_valid():
            form.save()
            messages.success(request, 'Task telah berhasil dibuat!')
            return redirect('todolist:show_todolist')

    context = {'form': form}
    return render(request, 'createtask.html', context)

def register(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')

    context = {'form': form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("todolist:show_todolist")
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

@login_required(login_url='/todolist/login/')
@csrf_exempt
def logout_user(request):
    logout(request)
    return redirect('todolist:login')

@login_required(login_url='/todolist/login/')
@csrf_exempt
def status(request, id):
    status = Task.objects.get(pk=id)
    if status.is_finished:
        status.is_finished = False
    else:
        status.is_finished = True
    status.save()
    return HttpResponseRedirect(reverse('todolist:show_todolist'))

@login_required(login_url='/todolist/login/')
@csrf_exempt
def delete(request, id):
    delete = Task.objects.get(pk=id)
    delete.delete()
    return HttpResponseRedirect(reverse('todolist:show_todolist'))

@login_required(login_url='/todolist/login/')
@csrf_exempt
def show_json_by_id(request):
    data = Task.objects.filter(user=request.user).order_by('id')
    return HttpResponse(serializers.serialize("json", data), content_type = "application/json")

@login_required(login_url='/todolist/login/')
@csrf_exempt
def create_task_ajax(request):
    if request.method == 'POST':
        user = request.user
        title = request.POST['title']
        description = request.POST['description']
        task_item = Task.objects.create(
            user=user, 
            title=title, 
            description=description
        )
        task_item.save()
        return JsonResponse({"instance": "Task successfully added!"}, status=200)


        

# Create your views here.

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p> {{ Name }}</p>

  <h5>Student ID: </h5>
  <p>{{ Student_ID }}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for item in catalogs %}
        <tr>
            <th>{{item.item_name}}</th>
            <th>{{item.item_price}}</th>
            <th>{{item.item_stock}}</th>
            <th>{{item.rating}}</th>
            <th>{{item.description}}</th>
            <th>{{item.item_url}}</th>
        </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

    {% block content %}

        <h5>Nama: </h5>
        <b>{{ Name }}</b>

        <h5>NPM: </h5>
        <b> {{ Student_ID }}</b>

        <table>
            <tr>
                <th>Watched</th>
                <th>Title</th>
                <th>Rating</th>
                <th>Release Date</th>
                <th>Review</th>
            </tr>

            {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
            {% for film in watchlist %}
                <tr>
                    <th>{{film.watched}}</th>
                    <th>{{film.title}}</th>
                    <th>{{film.rating}}</th>
                    <th>{{film.release_date}}</th>
                    <th>{{film.review}}</th>
                </tr>
            {% endfor %}
        </table>



    {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <link rel = "stylesheet" href="https://fonts.googleapis.com/css2?family=Lobster&family=Montserrat:wght@400;500;600&family=Nunito:wght@400;500;600;700;900&family=Poppins:wght@400;500;600&family=Roboto+Slab:wght@400;500;600&display=swap">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>

</html>

todolist/templates/createtask.html
{% extends 'base.html' %}

{% block content %}
<!doctype html>
<html lang="en">
    <head>
        <title>Add New Task</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        <link rel = "stylesheet" href="https://fonts.googleapis.com/css2?family=Lobster&family=Montserrat:wght@400;500;600&family=Nunito:wght@400;500;600;700;900&family=Poppins:wght@400;500;600&family=Roboto+Slab:wght@400;500;600&display=swap">
        <style>
            *{
                margin: 0;
                padding: 0;
                box-sizing: border-x;
                font-family: 'Poppins', sans-serif;
            }
            body{
                height: 100vh;
                background: linear-gradient(50deg, pink, rgb(254, 115, 138),rgb(252, 48, 82));
            }
            .createtask{
                position: relative;
                max-width: 900px;
                width: 100%;
            }
            .submitbutton{
                color: white;
                height: 55px;
                width: 80px;
                background:rgb(163, 39, 85);
                border: 3px solid pink;
                box-sizing: border-box;
                border-radius: 10px;
                margin: 15px 0 20px 0;
            }
            .submitbutton:hover{
                background:rgb(255, 72, 102);
            }

        </style>
    </head>
    <body>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
        <div class = "createtask"></div>
            <h4>Stay strong, you'll go through it!❤️</h4>  
            <p></p>
            <form action="" method="post">  
                {% csrf_token %}  
                <div class="table-responsive">
                    <table class="table table-borderless">
                        {{ form.as_table }}  
                        <tr>
                            <td></td>
                            <td><input class="submitbutton" type="submit" value="Save"></td>
                        </tr>
                    </table> 
                </div>
            </form>  
        </div>
    </body>
    {% endblock content %}
</html>

todolist/templates/login.html
{% extends 'base.html' %}

{% block content %}
<!doctype html>
<html lang="en">
    <head>
        <title>Sign in</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        <link rel = "stylesheet" href="https://fonts.googleapis.com/css2?family=Lobster&family=Montserrat:wght@400;500;600&family=Nunito:wght@400;500;600;700;900&family=Poppins:wght@400;500;600&family=Roboto+Slab:wght@400;500;600&display=swap">
        <style>

            *{
                margin: 0;
                padding: 0;
                box-sizing: border-box;
                font-family: 'Poppins', sans-serif;
            }
            body{
                height: 100vh;
                display: flex;
                align-items: center;
                justify-content: center;
                background: linear-gradient(50deg, pink, rgb(254, 115, 138),rgb(252, 48, 82));
            }
            .container{
                position: relative;
                max-width: 400px;
                width: 100%;
                background: white;
                box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);
                border-radius: 10px;
            }
            .container .login-form {
                padding: 30px;
            }

            .container .forms .title{
                position: relative;
                font-size: 30px;
                font-weight: 600;
            }

            .forms .title::before{
                content: '';
                position: absolute;
                left: 0;
                bottom: 0;
                height: 3px;
                width: 30px;
                background-color: pink;
                border-radius: 25px;
            }

            .login-form .btn{
                color: white;
                height: 42px;
                background: rgb(235, 132, 149);
                border: 3px solid pink;
                box-sizing: border-box;
                border-radius: 8px;
                margin: 10px 0 20px 0;
            }

            .btn:hover{
                background: rgb(255, 77, 107);
            }


        </style>
    </head>
    <body>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    
        <div class = "container">
            <div class="forms">
                <div class ="login-form">
                    <span class = "title">Sign in✨</span>
                    <p></p>

                        <form method="POST" action="">
                            {% csrf_token %}
                            <div class = "input-field">
                                <input type="text" name="username" placeholder="👤username" required>
                            </div>

                            <div class = "input-field">
                                <input type="password" name="password" placeholder="🔑password" required>
                            </div>
                      
                            <input class="btn login_btn" type="submit" value="Login">

                            <div class = "regist">
                                <span> Don't have an account? <a href="{% url 'todolist:register' %}">Sign Up</a></span>
                            </div>
                        </form>
                    </div>    

                    {% if messages %}
                    <ul>
                        {% for message in messages %}
                        <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}

                </div>

            </div>
        
        </div>

    </body>
    {% endblock content %}

</html>

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block meta %}
    <head>
        <title>ToDoList</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        <link rel = "stylesheet" href="https://fonts.googleapis.com/css2?family=Lobster&family=Montserrat:wght@400;500;600&family=Nunito:wght@400;500;600;700;900&family=Poppins:wght@400;500;600&family=Roboto+Slab:wght@400;500;600&display=swap">
        <style>
            *{
                margin: 0;
                padding: 0;
                box-sizing: border-box;
                font-family: 'Poppins', sans-serif;
            }
            body{
                height: 100vh;
                align-items: center;
                justify-content: center;
                background: linear-gradient(80deg, pink, rgb(254, 115, 138),rgb(252, 48, 82));
            }
            .container h1{
                font-size: 30px;
                font-weight: 600;
            }
            .container .btn-1{
                position: relative;
                color: white;
                height: 50px;
                width: 200px;
                font-size: 15px;
                background: rgb(180, 49, 71);
                border: 3px solid pink;
                box-sizing: border-box;
                border-radius: 8px;
                margin: 10px 0 20px 0;
            }
            .container .btn-2{
                position: relative;
                color: white;
                height: 50px;
                width: 200px;
                font-size: 15px;
                background: rgb(180, 49, 71);
                border: 3px solid pink;
                box-sizing: border-box;
                border-radius: 8px;
                margin: 10px 0 20px 0;
            }
            .row{
                padding-top: 20px;
                padding-bottom: 20px;
            }
            .card{
                background: rgb(255, 72, 102);
                width:100%;
                height: 100%;
                display: flex;
                justify-content: space-between;
                flex-direction: column;
                border: 3px solid pink;
                border-radius: 8px;
                margin: 10px 0 20px 0;
            }
            .card:hover{
                background: rgb(213, 77, 100);
                transform: scale(1.1);
            }

            .card .card-date{
                position: relative;
                font-style: normal;
                font-size: 15px;
                font-weight: 600;
            }

            .card .card-title{
                position: relative;
                font-style: normal;
                font-size: 25px;
                font-weight: 600;
            }

            p{
                font-style: normal;
                font-weight: 500;
                font-size: 16px;
                line-height: 21px;
                margin-left: 3px;
                margin-right: 3px;
            }
            .list-group-item.status .btn-card{
                border: none;
                outline: none;
                background: none;
            }

            .list-group-item.delete .btn-card{
                border: none;
                outline: none;
                background: none;
            }
         
            .list-group-item.status:hover{
                background: rgb(53, 179, 158)
            }
            .list-group-item.delete:hover{
                background: rgb(53, 179, 158)
            }
            .container .btn-1:hover{
                background-color: rgb(255, 72, 102);
            }
            .container .btn-2:hover{
                background-color: rgb(255, 72, 102);
            }

            .list-group-item.delete{
                background:rgb(14, 241, 188)
            }

            .list-group-item.status{
                background:rgb(14, 241, 188)
            }
            .modal-body .btn-close{
                position: relative;
                color: white;
                height: 50px;
                width: 200px;
                font-size: 15px;
                background: rgb(180, 49, 71);
                border: 3px solid pink;
                box-sizing: border-box;
                border-radius: 8px;
                margin: 10px 0 20px 0;
            }
            .modal-body .btn-save{
                position: relative;
                color: white;
                height: 50px;
                width: 200px;
                font-size: 15px;
                background: rgb(180, 49, 71);
                border: 3px solid pink;
                box-sizing: border-box;
                border-radius: 8px;
                margin: 10px 0 20px 0;
            }

            .modal-body .btn-save:hover{
                background-color: rgb(255, 72, 102);
            }
        </style>
    </head>
    {% endblock meta %}
    {% block content %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <body>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
        <section class="p-5"></section>
            <div class = "container">
                <h1>Welcome, {{username}}~!👋</h1>
                <!---<button class="btn-1" onclick="location.href='/todolist/create-task'">Create New Task</button>>--->
                <button type="button" class="btn-1" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Task</button>
                <button class="btn-2"><a href="{% url 'todolist:logout' %}">Logout</a></button>
                <h6>Here's your To Do List:</h6>
            </div>
            
            <div class = "modal" id="exampleModal" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
                <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="modalLabel">Create Task🌟</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form method="POST" action="">
                            {% csrf_token %}
                            <div class="mt-4">
                                <label for="Title">Title</label>
                            </div>
                            <input id ="title-controller" type="text" name="title" placeholder="Title" required class= "form-control">
                            <div class="mt-4">
                                <label for="description">Description</label>
                            </div>
                            <textarea id="description-controller" name="description" placeholder="Description" cols="30" rows="10" class="form-control" required></textarea>
                            <div class="modal-footer">
                                <button type="button" class="btn-close" data-bs-dismiss="modal">Close</button>
                                <button id="save-task" type="submit" class="btn-save" value="Submit" onclick="">Save changes</button>
                            </div>
                        </form>
                    </div>
                </div>
                </div>
            </div>
            <div id="todos-container" class="row text-center g-3">
                <!--
                {% for todo in to_do_list %}
                    <div class="col-md-4">
                        <div class="card">
                            <h2 class="card-date">{{todo.date}}</h2>
                            <h3 class="card-title">🌟{{todo.title}}🌟</p>
                            <p class="card-description">{{todo.description}}</p>
                            {% if todo.is_finished %}
                            <h6>Status: Finished✔️</h6>
                            {% else %}
                            <h6>Status: Not Finished Yet💪</h6>
                            {% endif %}
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item status">
                                    <a href="{% url 'todolist:status' todo.id %}" class="btn-card">Change Status</a>
                                </li>
                                <li class="list-group-item delete">
                                    <a href="{% url 'todolist:delete' todo.id %}" class="btn-card">Delete</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    {% endfor %}
                -->
            </div>
    </body>
    <script>
        function update(pk) {
        $.post({
            url: `status/${pk}/`,
            type: 'post',
            data: {},
            success: showtodolist
        })
        }

        function deleteTask(pk) {
            $.post({
                url: `delete/${pk}/`,
                type: 'post',
                data: {},
                success: showtodolist
            })
        }

        function createTask() {
            $.post({
                url: `add/`,
                type: 'post',
                data: {
                    'title': $('#title-controller').val(),
                    'description': $('#description-controller').val(),
                },
                success: showtodolist
            })
        }
        $(`#save-task`).attr('onclick', `createTask()`);

        function showtodolist() {
            $.get(
                './json',
                function (data) {
                    $('#todos-container').empty();
                    for (let i = 0; i < data.length; i++) {
                        $('#todos-container').append(
                            `<div  class="col-md-4">
                                <div class="card">
                                    <h2 class="card-date">${data[i].fields.date}</h2>
                                    <h3 class="card-title">${data[i].fields.title}</h3>
                                    <p class="card-description">${data[i].fields.description}</p>
                                    <p id="todo-mark-${i}" class="card-description"></p>
                                    <ul class="list-group list-group-flush">
                                        <li class="list-group-item status">
                                            <button type="button" onclick="" id="status-button-${i}" class="btn-card">Change Status</button>
                                        </li>
                                        <li class="list-group-item delete">
                                            <button type="button" onclick="" id="delete-button-${i}" class="btn-card">Delete</button>
                                        </li>
                                    </ul>
                                </div>
                            </div>`
                        )
                        if (data[i].fields.is_finished) {
                            $(`#todo-mark-${i}`).addClass('text-green-500').text('Finished✔️');
                        } else {
                            $(`#todo-mark-${i}`).addClass('text-red-600').text('Not Finished Yet💪');
                        }
                        $(`#status-button-${i}`).attr('onclick', `update(${data[i].pk})`);
                        $(`#delete-button-${i}`).attr('onclick', `deleteTask(${data[i].pk})`)
                    }
                }
            )
        }

        showtodolist();


    </script>
    {% endblock content %}
</html>